version: '3'

services:



  data_prod:
    restart: always
    image: "postgres:14-alpine"
    container_name: data_prod
    volumes:
        - ./data_prod/:/var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs
    ports:
        - "5439:5432"



  prod_api:
    restart: always
    build: ./project-name
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on: 
      - data_prod
    volumes:
      - ./project-name:/usr/src/app
      # - /usr/src/app/node_modules
   